# Generated by Django 5.0.6 on 2024-06-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('preco', models.FloatField()),
                ('dataVal', models.DateField()),
                ('dataPub', models.DateField(auto_now_add=True)),
                ('quantidade', models.IntegerField()),
            ],
        ),
    ]
