# Generated by Django 5.0.6 on 2024-06-24 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LojaApp', '0003_produtos_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendas',
            name='produto',
        ),
        migrations.DeleteModel(
            name='Produtos',
        ),
        migrations.DeleteModel(
            name='Vendas',
        ),
    ]
